export interface MemberItem {
  id: string;
  name: string;
  nameKana: string;
  email: string;
  memberType: string;
  lastAccessAt: string;
  companyName: string;
  status: string;
  createdAt: string;
}

export const DUMMY_MEMBERS: MemberItem[] = [
  {
    id: "M0001",
    name: "田中 太郎",
    nameKana: "たなか たろう",
    email: "tanaka@example.com",
    memberType: "BtoB",
    lastAccessAt: "2026.03.25 09:30",
    companyName: "株式会社サンプル",
    status: "アクティブ",
    createdAt: "2026.01.10",
  },
  {
    id: "M0002",
    name: "佐藤 花子",
    nameKana: "さとう はなこ",
    email: "sato@example.com",
    memberType: "BtoC",
    lastAccessAt: "2026.03.24 14:20",
    companyName: "佐藤商事",
    status: "アクティブ",
    createdAt: "2026.01.15",
  },
  {
    id: "M0003",
    name: "鈴木 一郎",
    nameKana: "すずき いちろう",
    email: "suzuki@example.com",
    memberType: "BtoB",
    lastAccessAt: "2026.03.20 11:00",
    companyName: "鈴木工業株式会社",
    status: "非アクティブ",
    createdAt: "2026.01.20",
  },
  {
    id: "M0004",
    name: "高橋 美咲",
    nameKana: "たかはし みさき",
    email: "takahashi@example.com",
    memberType: "BtoB",
    lastAccessAt: "2026.03.25 08:15",
    companyName: "高橋建設",
    status: "アクティブ",
    createdAt: "2026.02.01",
  },
  {
    id: "M0005",
    name: "伊藤 健二",
    nameKana: "いとう けんじ",
    email: "ito@example.com",
    memberType: "BtoC",
    lastAccessAt: "2026.03.22 16:45",
    companyName: "伊藤電機",
    status: "アクティブ",
    createdAt: "2026.02.05",
  },
  {
    id: "M0006",
    name: "渡辺 裕子",
    nameKana: "わたなべ ゆうこ",
    email: "watanabe@example.com",
    memberType: "BtoB",
    lastAccessAt: "2026.03.18 10:30",
    companyName: "渡辺物産",
    status: "非アクティブ",
    createdAt: "2026.02.10",
  },
  {
    id: "M0007",
    name: "山本 大輔",
    nameKana: "やまもと だいすけ",
    email: "yamamoto@example.com",
    memberType: "BtoB",
    lastAccessAt: "2026.03.25 07:50",
    companyName: "山本製作所",
    status: "アクティブ",
    createdAt: "2026.02.14",
  },
  {
    id: "M0008",
    name: "中村 真理",
    nameKana: "なかむら まり",
    email: "nakamura@example.com",
    memberType: "BtoC",
    lastAccessAt: "2026.03.23 13:10",
    companyName: "中村デザイン",
    status: "アクティブ",
    createdAt: "2026.02.20",
  },
  {
    id: "M0009",
    name: "小林 誠",
    nameKana: "こばやし まこと",
    email: "kobayashi@example.com",
    memberType: "BtoB",
    lastAccessAt: "2026.03.15 09:00",
    companyName: "小林テクノロジー",
    status: "非アクティブ",
    createdAt: "2026.02.25",
  },
  {
    id: "M0010",
    name: "加藤 愛",
    nameKana: "かとう あい",
    email: "kato@example.com",
    memberType: "BtoB",
    lastAccessAt: "2026.03.24 17:30",
    companyName: "加藤商会",
    status: "アクティブ",
    createdAt: "2026.03.01",
  },
  {
    id: "M0011",
    name: "吉田 拓也",
    nameKana: "よしだ たくや",
    email: "yoshida@example.com",
    memberType: "BtoC",
    lastAccessAt: "2026.03.21 12:00",
    companyName: "吉田興業",
    status: "アクティブ",
    createdAt: "2026.03.05",
  },
  {
    id: "M0012",
    name: "山田 由美",
    nameKana: "やまだ ゆみ",
    email: "yamada@example.com",
    memberType: "BtoB",
    lastAccessAt: "2026.03.10 15:20",
    companyName: "山田フーズ",
    status: "非アクティブ",
    createdAt: "2026.03.08",
  },
  {
    id: "M0013",
    name: "松本 翔",
    nameKana: "まつもと しょう",
    email: "matsumoto@example.com",
    memberType: "BtoB",
    lastAccessAt: "2026.03.25 10:45",
    companyName: "松本エンジニアリング",
    status: "アクティブ",
    createdAt: "2026.03.10",
  },
  {
    id: "M0014",
    name: "井上 さくら",
    nameKana: "いのうえ さくら",
    email: "inoue@example.com",
    memberType: "BtoC",
    lastAccessAt: "2026.03.19 08:30",
    companyName: "井上アート",
    status: "アクティブ",
    createdAt: "2026.03.15",
  },
  {
    id: "M0015",
    name: "木村 康平",
    nameKana: "きむら こうへい",
    email: "kimura@example.com",
    memberType: "BtoB",
    lastAccessAt: "2026.03.25 11:00",
    companyName: "木村産業株式会社",
    status: "アクティブ",
    createdAt: "2026.03.20",
  },
];
